# Generated by Django 5.0.6 on 2024-05-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('db', models.CharField(max_length=64)),
                ('collection', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stix_id', models.CharField(max_length=160)),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('stix_data_json', models.CharField(max_length=10000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='app.uploadtask')),
            ],
        ),
    ]
