# Generated by Django 5.0.6 on 2024-07-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploadtask_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectstatus',
            name='stix_data_json',
        ),
    ]
