name: Schemathesis and Path Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-schema-thesis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
    
          
      - name: Set .env for docker-compose
        run: |

            cat tests/st/.env.schemathesis >> .env
            cp tests/st/docker-compose.yml arango-compose.yml

            echo ==== env file start =====
            cat .env
            echo
            echo ==== env file end   =====

         
      - name: Start docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: |
            arango-compose.yml
            docker-compose.yml
          compose-flags:
            --env-file .env
            -p ats-action

      - name: Get IP addresses
        id: get_ip
        run: |
              IP_ADDRESS=$(docker network inspect -f '{{range.IPAM.Config}}{{.Gateway}}{{end}}' ats-action_default)
              echo "ip_address=$IP_ADDRESS" >> "$GITHUB_OUTPUT"
              echo "IP_ADDRESS=$IP_ADDRESS" >> "$GITHUB_OUTPUT"
              echo "SERVICE_BASE_URL=http://$IP_ADDRESS:8009/" >> "$GITHUB_OUTPUT"
              cat "$GITHUB_OUTPUT"

      - name: Wait for server to start
        run: |
              RETRY_DELAY=3
              RETRY_COUNT=10
              echo "Waiting for server to start"
              curl --retry-delay $RETRY_DELAY --retry $RETRY_COUNT --retry-connrefused ${{ steps.get_ip.outputs.SERVICE_BASE_URL }} > /dev/null
              if [ $? -ne 0 ]; then
                echo "exiting after waiting $(( $RETRY_DELAY * $RETRY_COUNT )) seconds for server to start"
                exit 1
              fi

      - name: create users, databases, collections and make uploads
        id: make_uploads
        run: |
            pip install -r tests/requirements.txt
            export SERVICE_BASE_URL="${{ steps.get_ip.outputs.SERVICE_BASE_URL }}"
            set -a; source tests/st/.env.schemathesis; set +a;
            export ARANGODB_HOST_URL=http://localhost:8529/

            python tests/create_accounts_and_databases.py
            python -m tests.upload_bundles

      - name: test all endpoints 1
        id: test-endpoints
        run: |
          export SERVICE_BASE_URL="${{ steps.get_ip.outputs.SERVICE_BASE_URL }}"

          pytest tests/

      - name: run schemathesis
        uses: schemathesis/action@v1
        # if: always()
        env:
          SCHEMATHESIS_HOOKS: tests.st.links
        with:
          schema: ${{ steps.get_ip.outputs.SERVICE_BASE_URL }}/api/schema/
          checks: all
          wait-for-schema: '30'
          args: '--generation-allow-x00 false'
